// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjfkVBUK0ORh-uZN8xaVtOSu0n9kp7S0',
    appId: '1:788901667016:web:1b5c1974d820304f6545fd',
    messagingSenderId: '788901667016',
    projectId: 'flutter-movil2',
    authDomain: 'flutter-movil2.firebaseapp.com',
    storageBucket: 'flutter-movil2.appspot.com',
    measurementId: 'G-1CP6N215Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aY64zGkGR9N23GnHaYn1tOHh7ablyH0',
    appId: '1:788901667016:android:a225e15d4488e9496545fd',
    messagingSenderId: '788901667016',
    projectId: 'flutter-movil2',
    storageBucket: 'flutter-movil2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03hrnZEQuSCHVPUd2NJQI5UwdopdWnag',
    appId: '1:788901667016:ios:23ede9dda5bdefb76545fd',
    messagingSenderId: '788901667016',
    projectId: 'flutter-movil2',
    storageBucket: 'flutter-movil2.appspot.com',
    iosClientId: '788901667016-njknjprqm0qg0p4jm8akanj8r0mib1r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMovil2',
  );
}
